### PR TITLE
config, gitignore, script

### PR DESCRIPTION
**Pull request by jffsun**
- added API key to config.js
- added config and DS_Store to .gitignore
- added API key to script.js
- reorganized file locations

### CODE REVIEW

**Comment by KevinNg2** [comment]
looks good

**Review by Young-Chhay — APPROVED** [review]
This look good Jeffrey ! this first pull looks good

**Review by KevinNg2 — APPROVED** [review]
looks good

**Review by drumholliday — APPROVED** [review]
Thanks

**Review by tony-PatMen — APPROVED** [review]
looking good

**Pull request merged**
