### PR TITLE
updated html & css

### PR DESCRIPTION
**Pull request by Young-Chhay**

### CODE REVIEW

**Review by KevinNg2 — APPROVED** [review]
lgtm

**Review by KevinNg2 — APPROVED** [review]
lgtm

**Review by jffsun — APPROVED** [review]
html and css looking much more developed. great work!

**Review by drumholliday — COMMENTED** [review]
Looks good

**Review by drumholliday — APPROVED** [review]

**Review by tony-PatMen — APPROVED** [review]
hello

**Pull request merged**
